name: SonarQube
on:
  pull_request_target:
    types: [labeled, opened, synchronize, reopened]
jobs:
  build:
    if: contains(github.event.pull_request.labels.*.name, 'approved-for-actions')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build and analyze
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn -B verify
